author: Ivan Topolsky
timezone: Europe/Zurich
title: User page
email: doktoy.yak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  User Pages
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dryak.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
